export const countriesArr = [
  { name: "Afghanistan", flag: "🇦🇫", code: "AF", phoneCode: "93" },
  { name: "Albania", flag: "🇦🇱", code: "AL", phoneCode: "355" },
  { name: "Algeria", flag: "🇩🇿", code: "DZ", phoneCode: "213" },
  { name: "Andorra", flag: "🇦🇩", code: "AD", phoneCode: "376" },
  { name: "Angola", flag: "🇦🇴", code: "AO", phoneCode: "244" },
  { name: "Antigua and Barbuda", flag: "🇦🇬", code: "AG", phoneCode: "1268" },
  { name: "Argentina", flag: "🇦🇷", code: "AR", phoneCode: "54" },
  { name: "Armenia", flag: "🇦🇲", code: "AM", phoneCode: "374" },
  { name: "Australia", flag: "🇦🇺", code: "AU", phoneCode: "61" },
  { name: "Austria", flag: "🇦🇹", code: "AT", phoneCode: "43" },
  { name: "Azerbaijan", flag: "🇦🇿", code: "AZ", phoneCode: "994" },
  { name: "Bahrain", flag: "🇧🇭", code: "BH", phoneCode: "973" },
  { name: "Bangladesh", flag: "🇧🇩", code: "BD", phoneCode: "880" },
  { name: "Barbados", flag: "🇧🇧", code: "BB", phoneCode: "1246" },
  { name: "Belarus", flag: "🇧🇾", code: "BY", phoneCode: "375" },
  { name: "Belgium", flag: "🇧🇪", code: "BE", phoneCode: "32" },
  { name: "Belize", flag: "🇧🇿", code: "BZ", phoneCode: "501" },
  { name: "Benin", flag: "🇧🇯", code: "BJ", phoneCode: "229" },
  { name: "Bhutan", flag: "🇧🇹", code: "BT", phoneCode: "975" },
  { name: "Bolivia", flag: "🇧🇴", code: "BO", phoneCode: "591" },
  { name: "Bosnia and Herzegovina", flag: "🇧🇦", code: "BA", phoneCode: "387" },
  { name: "Botswana", flag: "🇧🇼", code: "BW", phoneCode: "267" },
  { name: "Brazil", flag: "🇧🇷", code: "BR", phoneCode: "55" },
  { name: "Brunei Darussalam", flag: "🇧🇳", code: "BN", phoneCode: "673" },
  { name: "Bulgaria", flag: "🇧🇬", code: "BG", phoneCode: "359" },
  { name: "Burkina Faso", flag: "🇧🇫", code: "BF", phoneCode: "226" },
  { name: "Burundi", flag: "🇧🇮", code: "BI", phoneCode: "257" },
  { name: "Cambodia", flag: "🇰🇭", code: "KH", phoneCode: "855" },
  { name: "Cameroon", flag: "🇨🇲", code: "CM", phoneCode: "237" },
  { name: "Canada", flag: "🇨🇦", code: "CA", phoneCode: "1" },
  { name: "Cape Verde", flag: "🇨🇻", code: "CV", phoneCode: "238" },
  {
    name: "Central African Republic",
    flag: "🇨🇫",
    code: "CF",
    phoneCode: "236",
  },
  { name: "Chad", flag: "🇹🇩", code: "TD", phoneCode: "235" },
  { name: "Chile", flag: "🇨🇱", code: "CL", phoneCode: "56" },
  { name: "China", flag: "🇨🇳", code: "CN", phoneCode: "86" },
  { name: "Colombia", flag: "🇨🇴", code: "CO", phoneCode: "57" },
  { name: "Comoros", flag: "🇰🇲", code: "KM", phoneCode: "269" },
  {
    name: "Congo, Democratic Republic of the",
    flag: "🇨🇩",
    code: "CD",
    phoneCode: "243",
  },
  { name: "Congo, Republic of the", flag: "🇨🇬", code: "CG", phoneCode: "242" },
  { name: "Costa Rica", flag: "🇨🇷", code: "CR", phoneCode: "506" },
  { name: "Cote d'Ivoire", flag: "🇨🇮", code: "CI", phoneCode: "225" },
  { name: "Croatia", flag: "🇭🇷", code: "HR", phoneCode: "385" },
  { name: "Cuba", flag: "🇨🇺", code: "CU", phoneCode: "53" },
  { name: "Cyprus", flag: "🇨🇾", code: "CY", phoneCode: "357" },
  { name: "Czech Republic", flag: "🇨🇿", code: "CZ", phoneCode: "420" },
  { name: "Denmark", flag: "🇩🇰", code: "DK", phoneCode: "45" },
  { name: "Djibouti", flag: "🇩🇯", code: "DJ", phoneCode: "253" },
  { name: "Dominica", flag: "🇩🇲", code: "DM", phoneCode: "1767" },
  { name: "Dominican Republic", flag: "🇩🇴", code: "DO", phoneCode: "1809" },
  { name: "East Timor", flag: "🇹🇱", code: "TL", phoneCode: "670" },
  { name: "Ecuador", flag: "🇪🇨", code: "EC", phoneCode: "593" },
  { name: "Egypt", flag: "🇪🇬", code: "EG", phoneCode: "20" },
  { name: "El Salvador", flag: "🇸🇻", code: "SV", phoneCode: "503" },
  { name: "Equatorial Guinea", flag: "🇬🇶", code: "GQ", phoneCode: "240" },
  { name: "Eritrea", flag: "🇪🇷", code: "ER", phoneCode: "291" },
  { name: "Estonia", flag: "🇪🇪", code: "EE", phoneCode: "372" },
  { name: "Eswatini", flag: "🇸🇿", code: "SZ", phoneCode: "268" },
  { name: "Ethiopia", flag: "🇪🇹", code: "ET", phoneCode: "251" },
  { name: "Fiji", flag: "🇫🇯", code: "FJ", phoneCode: "679" },
  { name: "Finland", flag: "🇫🇮", code: "FI", phoneCode: "358" },
  { name: "France", flag: "🇫🇷", code: "FR", phoneCode: "33" },
  { name: "Gabon", flag: "🇬🇦", code: "GA", phoneCode: "241" },
  { name: "Gambia", flag: "🇬🇲", code: "GM", phoneCode: "220" },
  { name: "Georgia", flag: "🇬🇪", code: "GE", phoneCode: "995" },
  { name: "Germany", flag: "🇩🇪", code: "DE", phoneCode: "49" },
  { name: "Ghana", flag: "🇬🇭", code: "GH", phoneCode: "233" },
  { name: "Greece", flag: "🇬🇷", code: "GR", phoneCode: "30" },
  { name: "Grenada", flag: "🇬🇩", code: "GD", phoneCode: "1473" },
  { name: "Guatemala", flag: "🇬🇹", code: "GT", phoneCode: "502" },
  { name: "Guinea", flag: "🇬🇳", code: "GN", phoneCode: "224" },
  { name: "GuineaBissau", flag: "🇬🇼", code: "GW", phoneCode: "245" },
  { name: "Guyana", flag: "🇬🇾", code: "GY", phoneCode: "592" },
  { name: "Haiti", flag: "🇭🇹", code: "HT", phoneCode: "509" },
  { name: "Honduras", flag: "🇭🇳", code: "HN", phoneCode: "504" },
  { name: "Hungary", flag: "🇭🇺", code: "HU", phoneCode: "36" },
  { name: "Iceland", flag: "🇮🇸", code: "IS", phoneCode: "354" },
  { name: "India", flag: "🇮🇳", code: "IN", phoneCode: "91" },
  { name: "Indonesia", flag: "🇮🇩", code: "ID", phoneCode: "62" },
  { name: "Iran", flag: "🇮🇷", code: "IR", phoneCode: "98" },
  { name: "Iraq", flag: "🇮🇶", code: "IQ", phoneCode: "964" },
  { name: "Ireland", flag: "🇮🇪", code: "IE", phoneCode: "353" },
  { name: "Israel", flag: "🇮🇱", code: "IL", phoneCode: "972" },
  { name: "Italy", flag: "🇮🇹", code: "IT", phoneCode: "39" },
  { name: "Jamaica", flag: "🇯🇲", code: "JM", phoneCode: "1876" },
  { name: "Japan", flag: "🇯🇵", code: "JP", phoneCode: "81" },
  { name: "Jordan", flag: "🇯🇴", code: "JO", phoneCode: "962" },
  { name: "Kazakhstan", flag: "🇰🇿", code: "KZ", phoneCode: "7" },
  { name: "Kenya", flag: "🇰🇪", code: "KE", phoneCode: "254" },
  { name: "Kiribati", flag: "🇰🇮", code: "KI", phoneCode: "686" },
  { name: "Kuwait", flag: "🇰🇼", code: "KW", phoneCode: "965" },
  { name: "Kyrgyzstan", flag: "🇰🇬", code: "KG", phoneCode: "996" },
  { name: "Laos", flag: "🇱🇦", code: "LA", phoneCode: "856" },
  { name: "Latvia", flag: "🇱🇻", code: "LV", phoneCode: "371" },
  { name: "Lebanon", flag: "🇱🇧", code: "LB", phoneCode: "961" },
  { name: "Lesotho", flag: "🇱🇸", code: "LS", phoneCode: "266" },
  { name: "Liberia", flag: "🇱🇷", code: "LR", phoneCode: "231" },
  { name: "Libya", flag: "🇱🇾", code: "LY", phoneCode: "218" },
  { name: "Liechtenstein", flag: "🇱🇮", code: "LI", phoneCode: "423" },
  { name: "Lithuania", flag: "🇱🇹", code: "LT", phoneCode: "370" },
  { name: "Luxembourg", flag: "🇱🇺", code: "LU", phoneCode: "352" },
  {
    name: "Macedonia (the former Yugoslav Republic of)",
    flag: "🇲🇰",
    code: "MK",
    phoneCode: "389",
  },
  { name: "Madagascar", flag: "🇲🇬", code: "MG", phoneCode: "261" },
  { name: "Malawi", flag: "🇲🇼", code: "MW", phoneCode: "265" },
  { name: "Malaysia", flag: "🇲🇾", code: "MY", phoneCode: "60" },
  { name: "Maldives", flag: "🇲🇻", code: "MV", phoneCode: "960" },
  { name: "Mali", flag: "🇲🇱", code: "ML", phoneCode: "223" },
  { name: "Malta", flag: "🇲🇹", code: "MT", phoneCode: "356" },
  { name: "Marshall Islands", flag: "🇲🇭", code: "MH", phoneCode: "692" },
  { name: "Martinique", flag: "🇲🇶", code: "MQ", phoneCode: "596" },
  { name: "Mauritania", flag: "🇲🇷", code: "MR", phoneCode: "222" },
  { name: "Mauritius", flag: "🇲🇺", code: "MU", phoneCode: "230" },
  { name: "Mayotte", flag: "🇾🇹", code: "YT", phoneCode: "262" },
  { name: "Mexico", flag: "🇲🇽", code: "MX", phoneCode: "52" },
  {
    name: "Micronesia (Federated States of)",
    flag: "🇫🇲",
    code: "FM",
    phoneCode: "691",
  },
  { name: "Moldova (Republic of)", flag: "🇲🇩", code: "MD", phoneCode: "373" },
  { name: "Monaco", flag: "🇲🇨", code: "MC", phoneCode: "377" },
  { name: "Mongolia", flag: "🇲🇳", code: "MN", phoneCode: "976" },
  { name: "Montenegro", flag: "🇲🇪", code: "ME", phoneCode: "382" },
  { name: "Montserrat", flag: "🇲🇸", code: "MS", phoneCode: "1664" },
  { name: "Morocco", flag: "🇲🇦", code: "MA", phoneCode: "212" },
  { name: "Mozambique", flag: "🇲🇿", code: "MZ", phoneCode: "258" },
  { name: "Myanmar", flag: "🇲🇲", code: "MM", phoneCode: "95" },
  { name: "Namibia", flag: "🇳🇦", code: "NA", phoneCode: "264" },
  { name: "Nauru", flag: "🇳🇷", code: "NR", phoneCode: "674" },
  { name: "Nepal", flag: "🇳🇵", code: "NP", phoneCode: "977" },
  { name: "Netherlands", flag: "🇳🇱", code: "NL", phoneCode: "31" },
  { name: "New Zealand", flag: "🇳🇿", code: "NZ", phoneCode: "64" },
  { name: "Nicaragua", flag: "🇳🇮", code: "NI", phoneCode: "505" },
  { name: "Niger", flag: "🇳🇪", code: "NE", phoneCode: "227" },
  { name: "Nigeria", flag: "🇳🇬", code: "NG", phoneCode: "234" },
  { name: "North Korea", flag: "🇰🇵", code: "KP", phoneCode: "850" },
  { name: "North Macedonia", flag: "🇲🇰", code: "MK", phoneCode: "389" },
  { name: "Norway", flag: "🇳🇴", code: "NO", phoneCode: "47" },
  { name: "Oman", flag: "🇴🇲", code: "OM", phoneCode: "968" },
  { name: "Pakistan", flag: "🇵🇰", code: "PK", phoneCode: "92" },
  { name: "Palau", flag: "🇵🇼", code: "PW", phoneCode: "680" },
  { name: "Panama", flag: "🇵🇦", code: "PA", phoneCode: "507" },
  { name: "Papua New Guinea", flag: "🇵🇬", code: "PG", phoneCode: "675" },
  { name: "Paraguay", flag: "🇵🇾", code: "PY", phoneCode: "595" },
  { name: "Peru", flag: "🇵🇪", code: "PE", phoneCode: "51" },
  { name: "Philippines", flag: "🇵🇭", code: "PH", phoneCode: "63" },
  { name: "Poland", flag: "🇵🇱", code: "PL", phoneCode: "48" },
  { name: "Portugal", flag: "🇵🇹", code: "PT", phoneCode: "351" },
  { name: "Qatar", flag: "🇶🇦", code: "QA", phoneCode: "974" },
  { name: "Romania", flag: "🇷🇴", code: "RO", phoneCode: "40" },
  { name: "Russia", flag: "🇷🇺", code: "RU", phoneCode: "7" },
  { name: "Rwanda", flag: "🇷🇼", code: "RW", phoneCode: "250" },
  { name: "Sao Tome and Principe", flag: "🇸🇹", code: "ST", phoneCode: "239" },
  { name: "Saudi Arabia", flag: "🇸🇦", code: "SA", phoneCode: "966" },
  { name: "Senegal", flag: "🇸🇳", code: "SN", phoneCode: "221" },
  { name: "Serbia", flag: "🇷🇸", code: "RS", phoneCode: "381" },
  { name: "Seychelles", flag: "🇸🇨", code: "SC", phoneCode: "248" },
  { name: "Sierra Leone", flag: "🇸🇱", code: "SL", phoneCode: "232" },
  { name: "Singapore", flag: "🇸🇬", code: "SG", phoneCode: "65" },
  { name: "Slovakia", flag: "🇸🇰", code: "SK", phoneCode: "421" },
  { name: "Slovenia", flag: "🇸🇮", code: "SI", phoneCode: "386" },
  { name: "Solomon Islands", flag: "🇸🇧", code: "SB", phoneCode: "677" },
  { name: "Somalia", flag: "🇸🇴", code: "SO", phoneCode: "252" },
  { name: "South Africa", flag: "🇿🇦", code: "ZA", phoneCode: "27" },
  { name: "South Sudan", flag: "🇸🇸", code: "SS", phoneCode: "211" },
  { name: "Spain", flag: "🇪🇸", code: "ES", phoneCode: "34" },
  { name: "Sri Lanka", flag: "🇱🇰", code: "LK", phoneCode: "94" },
  { name: "Sudan", flag: "🇸🇩", code: "SD", phoneCode: "249" },
  { name: "Suriname", flag: "🇸🇷", code: "SR", phoneCode: "597" },
  { name: "Swaziland", flag: "🇸🇿", code: "SZ", phoneCode: "268" },
  { name: "Sweden", flag: "🇸🇪", code: "SE", phoneCode: "46" },
  { name: "Switzerland", flag: "🇨🇭", code: "CH", phoneCode: "41" },
  { name: "Syria", flag: "🇸🇾", code: "SY", phoneCode: "963" },
  { name: "Thailand", flag: "🇹🇭", code: "TH", phoneCode: "66" },
  { name: "Timor-Leste", flag: "🇹🇱", code: "TL", phoneCode: "670" },
  { name: "Togo", flag: "🇹🇬", code: "TG", phoneCode: "228" },
  { name: "Tonga", flag: "🇹🇴", code: "TO", phoneCode: "676" },
  { name: "Trinidad and Tobago", flag: "🇹🇹", code: "TT", phoneCode: "1868" },
  { name: "Tunisia", flag: "🇹🇳", code: "TN", phoneCode: "216" },
  { name: "Turkey", flag: "🇹🇷", code: "TR", phoneCode: "90" },
  { name: "Turkmenistan", flag: "🇹🇲", code: "TM", phoneCode: "993" },
  { name: "Tuvalu", flag: "🇹🇻", code: "TV", phoneCode: "688" },
  { name: "Uganda", flag: "🇺🇬", code: "UG", phoneCode: "256" },
  { name: "Ukraine", flag: "🇺🇦", code: "UA", phoneCode: "380" },
  { name: "United Arab Emirates", flag: "🇦🇪", code: "AE", phoneCode: "971" },
  { name: "United Kingdom", flag: "🇬🇧", code: "GB", phoneCode: "44" },
  { name: "United States of America", flag: "🇺🇸", code: "US", phoneCode: "1" },
  { name: "Uruguay", flag: "🇺🇾", code: "UY", phoneCode: "598" },
  { name: "Uzbekistan", flag: "🇺🇿", code: "UZ", phoneCode: "998" },
  { name: "Vanuatu", flag: "🇻🇺", code: "VU", phoneCode: "678" },
  { name: "Venezuela", flag: "🇻🇪", code: "VE", phoneCode: "58" },
  { name: "Vietnam", flag: "🇻🇳", code: "VN", phoneCode: "84" },
  { name: "Yemen", flag: "🇾🇪", code: "YE", phoneCode: "967" },
  { name: "Zambia", flag: "🇿🇲", code: "ZM", phoneCode: "260" },
  { name: "Zimbabwe", flag: "🇿🇼", code: "ZW", phoneCode: "263" },
];
